In [1]:
# importing numpy package as np
import numpy as np

In [3]:
an_array = np.array([10, 10, 1999]) # creating an 1-D array
print(an_array)
print(type(an_array)) # print the type of the array i.e. numpy.ndarray

[  10   10 1999]
<class 'numpy.ndarray'>


In [4]:
print(an_array.shape) # print the dimensions of the nd-array
# this is a vector

(3,)


In [5]:
print(an_array[0], an_array[1], an_array[2]) # priniting the values of the array

10 10 1999


In [7]:
an_array[1] = 11 # np arrays are mutable
# an_array[1] = '11' # this gives an error since all entries in the array must be of same type 
print(an_array)

[  10   11 1999]


In [12]:
v = np.array([[10, 20], [11, 22], [12, 24]])
print(v.shape) # we get (3, 2) as the output
# this is a rank 3 array, rank is equal to the number of rows in the array
print(v[0][1])

(3, 2)
20


### Other useful numpy features

In [14]:
# create an array of zeros
zer = np.zeros((4, 1))
print(zer)

[[0.]
 [0.]
 [0.]
 [0.]]


In [18]:
# create an array prefilled with some other values
two = np.full((4, 1), 2)
print(two)
print(two.shape)

[[2]
 [2]
 [2]
 [2]]
(4, 1)


In [19]:
# create an array filled wih ones
one = np.ones((2, 2))
print(one)
print(one.shape)


[[1. 1.]
 [1. 1.]]
(2, 2)


In [22]:
# create a identity array
diag = np.eye(3,3) # does not give an error in case of rectangular shpe, has 1 only on the principal diagonal
print(diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
diagR = np.eye(3, 4)
print(diagR)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [26]:
rank1 = np.ones(2)
print(rank1)
rank2 = np.ones((1, 2))
print(rank2)

[1. 1.]
[[1. 1.]]


*Creating an array filled with random vales*

In [27]:
rArr = np.random.random((2, 3))
print(rArr)

[[0.02706081 0.66666488 0.51060438]
 [0.73076531 0.49774909 0.46025327]]


## Array Indexing

In [30]:
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [34]:
slic = an_array[0:2, 1:3]
print(slic)
print(slic.shape)

[[12 99]
 [22 23]]
(2, 2)


In [35]:
slic[0][1] = 99 # modifying the sliced array modifies the underlying array
print(an_array)

[[11 12 99 14]
 [21 22 23 24]
 [31 32 33 34]]


**Slices are only references to the same underlying array**

In [36]:
# to create a copy of the slice;
slicD = np.array(an_array[0:2, 1:3])

In [37]:
slicD[0][1] = 444
print(an_array[0][2]) # modifying slicD does not change the underlying array as it is a copy and not a reference
print(slicD[0][1])

99
444


## Use both Integer Indexing and Slicing

In [84]:
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [85]:
first_column = np.array(an_array[:, 0])
first_row = np.array(an_array[0, :])
print("First column:", first_column)
print(first_column.shape)
print("First row:", first_row)
print(first_row.shape)
# using the signle integer for slicing is a special case, it return a rank 1 matrix
# notice the single []

First column: [11 21 31]
(3,)
First row: [11 12 13 14]
(4,)


In [86]:
# using 0:1 to refer to the first row will not return a rank 1 matrix, rather a rank 2 matrix
r2 = np.array(an_array[0:1, :])
print(r2, r2.shape)
#notice the [[]]

[[11 12 13 14]] (1, 4)


In [87]:
# np.arange function
# return evenly spaced integers in the mentioned half-open interval
x = np.arange(1, 10, 2)
print(type(x), x, x.shape)

<class 'numpy.ndarray'> [1 3 5 7 9] (5,)


In [88]:
x = [0, 1, 2]
y = np.arange(1, 4, 1)
k = zip(x, y)
for i, j in k:
    print(i, ",", j)


0 , 1
1 , 2
2 , 3


In [89]:
print(an_array[x, y])
an_array[x, y] += 10000
print(an_array[x, y])
# we can also use array of indices in addition to : and integer values for slicing

[12 23 34]
[10012 10023 10034]


## Boolean Indexing

In [90]:
an_array = np.array([[11, 12], [21, 22], [31, 32]])
print(an_array, an_array.shape)

[[11 12]
 [21 22]
 [31 32]] (3, 2)


In [92]:
fil = an_array > 15
print(filter, type(fil), fil.shape)

[[False False]
 [ True  True]
 [ True  True]] <class 'numpy.ndarray'> (3, 2)


In [95]:
print(an_array[fil], an_array[fil].shape)
# only selects those values at which boolean value is true

[21 22 31 32] (4,)


In [96]:
# using this we can change all the values in an array which meet a particular critera, or apply a logical filter
an_array[an_array % 2 == 0] = 0
print(an_array)

[[11  0]
 [21  0]
 [31  0]]


## NdArray Datatypes and Operations

In [97]:
ex1 = np.array([1.1, 2.2, 3.3])
print(ex1.dtype)

float64


In [99]:
ex1 = np.array([1.1, 2.2, 3.3], dtype = np.int64) # we can force floats into integers
print(ex1, ex1.dtype)

[1 2 3] int64


In [108]:
ex1 = np.array(['12', '2', '3'], dtype = np.int64)
print(ex1.dtype)
print(ex1)

int64
[12  2  3]


In [118]:
ex1 += 23
#ex1 += 23.65 causes error as cannot add float to integer

In [119]:
ex1

array([81, 71, 72], dtype=int64)

In [129]:
a1 = np.array([111, 222, 323])
a2 = np.array([2, 0.4, 4.5])
print(a1 + a2)
print(a1 - a2)
# the result upcasts to float to avoid losing precision

[113.  222.4 327.5]
[109.  221.6 318.5]


In [130]:
# exponentiation of array
print(np.exp(a1))

[1.60948707e+048 2.59044862e+096 1.89285634e+140]


In [133]:
#division of array
print(a1 / a2)

[ 55.5        555.          71.77777778]


In [134]:
# element wise multiplication of array
print(a1 * a2)

[ 222.    88.8 1453.5]


## Statistical, Sorting and Set Operations

In [142]:
# create a 2x5 array filled with random values from normal distribution
an_array = 10 * np.random.randn(2, 4)
print(an_array)

[[ -4.21439382 -12.96757233  -8.41369557   5.66781626]
 [-10.25391896   8.51226365  -8.23682799   4.54312913]]


In [144]:
# finding the mean for the array
x = np.mean(an_array)
print(x)

-3.170399952602035


In [146]:
# compute row wise mean
row_wise = np.mean(an_array, axis = 1)
print(row_wise)

[-4.98196137 -1.35883854]


In [147]:
# compute column wise mean
col_wise = np.mean(an_array, axis = 0)
print(col_wise)

[-7.23415639 -2.22765434 -8.32526178  5.1054727 ]


In [148]:
# compute column wise sum
col_sum = np.sum(an_array, axis = 0)
print(col_sum)

[-14.46831278  -4.45530868 -16.65052355  10.21094539]


In [150]:
#compute row wise sum
row_sum = np.sum(an_array, axis = 1)
print(row_sum)

[-19.92784546  -5.43535416]


In [151]:
#compute sum of array
s = np.sum(an_array)
print(s)

-25.36319962081628


In [152]:
# compute the median  by row
md = np.median(an_array, axis = 1)
print(md)

[-6.3140447  -1.84684943]


In [158]:
# sort an array
copy = np.array(an_array)
copy.sort()
print(copy)
print(an_array)

[[-12.96757233  -8.41369557  -4.21439382   5.66781626]
 [-10.25391896  -8.23682799   4.54312913   8.51226365]]
[[ -4.21439382 -12.96757233  -8.41369557   5.66781626]
 [-10.25391896   8.51226365  -8.23682799   4.54312913]]


In [159]:
# sort in place
an_array.sort()
print(an_array)

[[-12.96757233  -8.41369557  -4.21439382   5.66781626]
 [-10.25391896  -8.23682799   4.54312913   8.51226365]]


In [163]:
# find out unique elements from an array
x = [[1, 2, 2], [3, 5, 3], [4, 2, 1]]
un = np.unique(x)
print(un, un.shape, type(un))


[1 2 3 4 5] (5,) <class 'numpy.ndarray'>


## Using Set Operations with Np.arrays

In [177]:
a1 = np.array(['bulb', 'chair', 'desk'])
a2 = np.array(['bulb', 'table', 'sofa'])

In [178]:
inter = np.intersect1d(a1, a2) # can be run with multi-dim arrays too.
print(inter)

['bulb']


In [179]:
un = np.union1d(a1, a2)
print(un)

['bulb' 'chair' 'desk' 'sofa' 'table']


In [181]:
diff = np.setdiff1d(a1, a2) # s1 - s2 i.e. elements in s1 that are not there in s2
print(diff)

['chair' 'desk']


In [182]:
com = np.in1d(a1, a2) # return array of boolean values 
# true for values common in a1 and a2, false otherwise
print(com)

[ True False False]


In [186]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x[:2,]) # this works
print(x[,:2]) # this returns an error

[[1 2 3]
 [4 5 6]]


## BroadCasting

In [188]:
arr = np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [189]:
add_rows = np.array([1, 2, 3])
print(arr + add_rows)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [196]:
add_cols = np.array([1, 2, 3, 4])
add_cols = add_cols.T
print(add_cols) # this creates a vector only, we need to create a 1 x 4 matrix to have a transpose of 4 x 1
add_cols = np.array([[1, 2, 3, 4]])
add_cols = add_cols.T
print(add_cols, arr + add_cols)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]] [[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [198]:
add_scalar = np.array([[1]])
print(arr + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [199]:
add_scalar2 = np.array([1])
print(arr + add_scalar2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [200]:
print(arr + 1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
